;; https://adventofcode.com/2023/day/1

(require 'aoc2023)

(defun join-first-and-last-num (lst)
  (->> (list (number-to-string (car lst))
             (number-to-string (car (last lst))))
       (string-join)
       (string-to-number)))

(defun double-first-num (lst)
  (->> (list (number-to-string (car lst))
             (number-to-string (car lst)))
       (string-join)
       (string-to-number)))

(defun determine-calibration (lst)
  (cond ((= 1 (length lst)) (double-first-num lst))
        (t (join-first-and-last-num lst))))

(defun collect (acc cur)
  (let ((num (string-to-number cur)))
    (cond ((equal cur "0") (append acc (list 0)))
          ((> num 0) (append acc (list num)))
          (t acc))))

(defun collect-numbers (lst)
  (cl-reduce 'collect lst :initial-value '()))

(defun collect-v2 (acc cur)
  (let* ((num (string-to-number cur))
         (lst (car acc))
         (buf (cdr acc))
         (nxt (string-join (list buf cur))))
    (cond ((equal cur "0")
           (append acc (list 0)))
          ((> num 0)
           (cons (append lst (list num)) nil))
          ((cl-search "one" nxt)
           (cons (append lst (list 1)) "e"))
          ((cl-search "two" nxt)
           (cons (append lst (list 2)) "o"))
          ((cl-search "three" nxt)
           (cons (append lst (list 3)) "e"))
          ((cl-search "four" nxt)
           (cons (append lst (list 4)) nil))
          ((cl-search "five" nxt)
           (cons (append lst (list 5)) "e"))
          ((cl-search "six" nxt)
           (cons (append lst (list 6)) nil))
          ((cl-search "seven" nxt)
           (cons (append lst (list 7)) "n"))
          ((cl-search "eight" nxt)
           (cons (append lst (list 8)) "t"))
          ((cl-search "nine" nxt)
           (cons (append lst (list 9)) "e"))
          (t (cons lst nxt)))))

(defun collect-numbers-v2 (lst)
  (car (cl-reduce 'collect-v2 lst :initial-value '())))

(defun split (str)
  (split-string str "" t))

(defun 2023-01-part1 (input)
  (->> (mapcar 'split input)
       (mapcar 'collect-numbers)
       (mapcar 'determine-calibration)
       (apply '+)))

(defun 2023-01-part2 (input)
  (->> (mapcar 'split input)
       (mapcar 'collect-numbers-v2)
       (mapcar 'determine-calibration)
       (apply '+)))

(defconst testfile (expand-file-name "input/01.test.txt"))
(defconst inputfile (expand-file-name "input/01.input.txt"))
(defconst testfile-pt2 (expand-file-name "input/01.test.pt2.txt"))

(defcheck 2023-01-part1 testfile 142)
(defcheck 2023-01-part1 inputfile 54927)
(defcheck 2023-01-part2 testfile-pt2 281)
(defcheck 2023-01-part2 inputfile 54581)

(solve "2023-01")
